# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/renseigmnement_carte_Id.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listeEnregistrement = QtWidgets.QTabWidget(self.centralwidget)
        self.listeEnregistrement.setGeometry(QtCore.QRect(0, 0, 1221, 661))
        self.listeEnregistrement.setMinimumSize(QtCore.QSize(0, 0))
        self.listeEnregistrement.setStyleSheet("background-color:lightblue;\n"
"font:Arial 30 bold;\n"
"\n"
"")
        self.listeEnregistrement.setTabPosition(QtWidgets.QTabWidget.North)
        self.listeEnregistrement.setIconSize(QtCore.QSize(50, 50))
        self.listeEnregistrement.setObjectName("listeEnregistrement")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btn_delete = QtWidgets.QPushButton(self.tab_2)
        self.btn_delete.setGeometry(QtCore.QRect(320, 20, 101, 41))
        self.btn_delete.setStyleSheet("QPushButton{\n"
"background-color:#d41c1c;\n"
"color:white;\n"
"font:Italic 16 bold;\n"
"border-radius:9px\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.btn_update = QtWidgets.QPushButton(self.tab_2)
        self.btn_update.setGeometry(QtCore.QRect(430, 20, 101, 41))
        self.btn_update.setStyleSheet("QPushButton{\n"
"background-color:#2ad482;\n"
"color:white;\n"
"font:Italic 16 bold;\n"
"border-radius:9px\n"
"}")
        self.btn_update.setObjectName("btn_update")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 70, 1261, 561))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("background-color: lightgrey;\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setLineWidth(3)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setRowCount(21)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(100, 218, 243))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(112, 238, 160))
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(149)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.name_search = QtWidgets.QLineEdit(self.tab_2)
        self.name_search.setGeometry(QtCore.QRect(570, 20, 261, 41))
        self.name_search.setStyleSheet("QLineEdit{\n"
"\n"
"background-color:white;\n"
"}")
        self.name_search.setObjectName("name_search")
        self.btn_search = QtWidgets.QPushButton(self.tab_2)
        self.btn_search.setGeometry(QtCore.QRect(840, 20, 81, 41))
        self.btn_search.setStyleSheet("QPushButton{\n"
"background-color:lightblue;\n"
"color:white;\n"
"font:Italic 28 bold;\n"
"border-radius:9px;\n"
"border:1px solid white;\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.btn_refresh = QtWidgets.QPushButton(self.tab_2)
        self.btn_refresh.setGeometry(QtCore.QRect(1140, 20, 71, 41))
        self.btn_refresh.setStyleSheet("QPushButton{\n"
"background-color:lightblue;\n"
"color:white;\n"
"font:Italic 16 bold;\n"
"border-radius:9px;\n"
"border:1px solid white;\n"
"}")
        self.btn_refresh.setIconSize(QtCore.QSize(35, 35))
        self.btn_refresh.setObjectName("btn_refresh")
        self.listeEnregistrement.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1231, 611))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:lightblue;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 100, 421, 31))
        self.label.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 210, 421, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 300, 421, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 410, 421, 31))
        self.label_4.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(490, 210, 461, 31))
        self.label_5.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(490, 100, 461, 31))
        self.label_6.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(490, 410, 461, 31))
        self.label_9.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.nom = QtWidgets.QLineEdit(self.frame)
        self.nom.setGeometry(QtCore.QRect(50, 130, 421, 31))
        self.nom.setStyleSheet("QLineEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.nom.setClearButtonEnabled(True)
        self.nom.setObjectName("nom")
        self.prenom = QtWidgets.QLineEdit(self.frame)
        self.prenom.setGeometry(QtCore.QRect(50, 240, 421, 31))
        self.prenom.setStyleSheet("QLineEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.prenom.setClearButtonEnabled(True)
        self.prenom.setObjectName("prenom")
        self.lieu = QtWidgets.QLineEdit(self.frame)
        self.lieu.setGeometry(QtCore.QRect(50, 440, 421, 31))
        self.lieu.setStyleSheet("QLineEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.lieu.setClearButtonEnabled(True)
        self.lieu.setObjectName("lieu")
        self.taille = QtWidgets.QLineEdit(self.frame)
        self.taille.setGeometry(QtCore.QRect(490, 130, 461, 31))
        self.taille.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.taille.setStyleSheet("QLineEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.taille.setClearButtonEnabled(True)
        self.taille.setObjectName("taille")
        self.btn_photo = QtWidgets.QPushButton(self.frame)
        self.btn_photo.setGeometry(QtCore.QRect(1020, 300, 141, 31))
        self.btn_photo.setStyleSheet("QPushButton{\n"
"background-color:lightgreen;\n"
"color:white;\n"
"font:Italic 14 bold;\n"
"border:2px solid white;\n"
"}")
        self.btn_photo.setObjectName("btn_photo")
        self.btn_annuler = QtWidgets.QPushButton(self.frame)
        self.btn_annuler.setGeometry(QtCore.QRect(580, 540, 131, 31))
        self.btn_annuler.setStyleSheet("QPushButton{\n"
"background-color:#e34040;\n"
"color:white;\n"
"font:Italic 14 bold;\n"
"border:2px solid white;\n"
"border-radius:12px;\n"
"}")
        self.btn_annuler.setAutoRepeatDelay(300)
        self.btn_annuler.setAutoRepeatInterval(100)
        self.btn_annuler.setObjectName("btn_annuler")
        self.btn_valider1 = QtWidgets.QPushButton(self.frame)
        self.btn_valider1.setGeometry(QtCore.QRect(750, 540, 151, 31))
        self.btn_valider1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_valider1.setStyleSheet("QPushButton{\n"
"background-color:#30ff98;\n"
"color:white;\n"
"font:Italic 14 bold;\n"
"border:2px solid white;\n"
"border-radius:12px;\n"
"}")
        self.btn_valider1.setObjectName("btn_valider1")
        self.comboBoxSexe = QtWidgets.QComboBox(self.frame)
        self.comboBoxSexe.setGeometry(QtCore.QRect(490, 240, 461, 31))
        self.comboBoxSexe.setStyleSheet("QComboBox{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.comboBoxSexe.setMaxCount(5)
        self.comboBoxSexe.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBoxSexe.setObjectName("comboBoxSexe")
        self.comboBoxSexe.addItem("")
        self.comboBoxSexe.addItem("")
        self.comboBoxSexe.addItem("")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(490, 300, 461, 31))
        self.label_10.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.nationalite = QtWidgets.QLineEdit(self.frame)
        self.nationalite.setGeometry(QtCore.QRect(490, 330, 461, 31))
        self.nationalite.setStyleSheet("QLineEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.nationalite.setClearButtonEnabled(True)
        self.nationalite.setObjectName("nationalite")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(-20, 20, 1251, 51))
        self.label_7.setStyleSheet("QLabel{\n"
"color:red;\n"
"shadow:12px;}")
        self.label_7.setObjectName("label_7")
        self.dateNaissance = QtWidgets.QDateEdit(self.frame)
        self.dateNaissance.setGeometry(QtCore.QRect(50, 330, 421, 31))
        self.dateNaissance.setStyleSheet("QDateEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.dateNaissance.setCalendarPopup(True)
        self.dateNaissance.setDate(QtCore.QDate(2022, 3, 18))
        self.dateNaissance.setObjectName("dateNaissance")
        self.Validite = QtWidgets.QDateEdit(self.frame)
        self.Validite.setGeometry(QtCore.QRect(490, 440, 461, 31))
        self.Validite.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Validite.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Validite.setAutoFillBackground(False)
        self.Validite.setStyleSheet("QDateEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.Validite.setSpecialValueText("")
        self.Validite.setProperty("showGroupSeparator", True)
        self.Validite.setCalendarPopup(True)
        self.Validite.setTimeSpec(QtCore.Qt.UTC)
        self.Validite.setObjectName("Validite")
        self.labPhoto = QtWidgets.QLabel(self.frame)
        self.labPhoto.setGeometry(QtCore.QRect(1020, 100, 141, 161))
        self.labPhoto.setStyleSheet("QLabel{\n"
"border:1px solid white;\n"
"}")
        self.labPhoto.setScaledContents(True)
        self.labPhoto.setObjectName("labPhoto")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(50, 530, 421, 31))
        self.email.setAutoFillBackground(False)
        self.email.setStyleSheet("QLineEdit{\n"
"border-top-left-radius:12px;\n"
"border-top-right-radius:12px;\n"
"background-color:white;\n"
"}")
        self.email.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email.setCursorPosition(0)
        self.email.setClearButtonEnabled(True)
        self.email.setObjectName("email")
        self.email_Label = QtWidgets.QLabel(self.frame)
        self.email_Label.setGeometry(QtCore.QRect(50, 500, 421, 31))
        self.email_Label.setStyleSheet("QLabel{\n"
"font: italic 13pt \"Georgia\";\n"
"background-color:#5892bf;\n"
"border-bottom-left-radius:13px;\n"
"border-bottom-right-radius:13px;\n"
"padding-left:15px;\n"
"}")
        self.email_Label.setIndent(-5)
        self.email_Label.setObjectName("email_Label")
        self.listeEnregistrement.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listeEnregistrement.setCurrentIndex(0)
        self.comboBoxSexe.setCurrentIndex(0)
        self.btn_annuler.clicked.connect(self.nationalite.clear) # type: ignore
        self.btn_annuler.clicked.connect(self.lieu.clear) # type: ignore
        self.btn_annuler.clicked.connect(self.nom.clear) # type: ignore
        self.btn_annuler.clicked.connect(self.prenom.clear) # type: ignore
        self.btn_annuler.clicked.connect(self.taille.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_delete.setText(_translate("MainWindow", "SUPPRIMER"))
        self.btn_update.setText(_translate("MainWindow", "MODIFIER"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NOM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PRENOM"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DATE NAISSANCE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LIEU NAISSANCE"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TAILLE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SEXE"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "NATIONALITE"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "VALIDITE"))
        self.name_search.setPlaceholderText(_translate("MainWindow", "Ajouter un element "))
        self.btn_search.setText(_translate("MainWindow", "search"))
        self.btn_refresh.setText(_translate("MainWindow", "rafraichie"))
        self.listeEnregistrement.setTabText(self.listeEnregistrement.indexOf(self.tab_2), _translate("MainWindow", "liste"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Nom</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Prenom</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Date de naissance</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Lieu de naissance</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Sexe</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">     Taille</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Validité</span></p></body></html>"))
        self.nom.setPlaceholderText(_translate("MainWindow", "Entrez le nom"))
        self.prenom.setPlaceholderText(_translate("MainWindow", "Entrez le  prenom"))
        self.lieu.setPlaceholderText(_translate("MainWindow", "Entrez le lieu de naissance"))
        self.taille.setPlaceholderText(_translate("MainWindow", "Entrez la  taille"))
        self.btn_photo.setText(_translate("MainWindow", "Photo"))
        self.btn_annuler.setText(_translate("MainWindow", "Annuler"))
        self.btn_valider1.setText(_translate("MainWindow", "Valider"))
        self.comboBoxSexe.setCurrentText(_translate("MainWindow", "Masculin"))
        self.comboBoxSexe.setPlaceholderText(_translate("MainWindow", "choisir"))
        self.comboBoxSexe.setItemText(0, _translate("MainWindow", "Masculin"))
        self.comboBoxSexe.setItemText(1, _translate("MainWindow", "Feminin"))
        self.comboBoxSexe.setItemText(2, _translate("MainWindow", "Autre"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">NATIONALITE</span></p><p><br/></p></body></html>"))
        self.nationalite.setPlaceholderText(_translate("MainWindow", "Entrez la nationalité"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">PRODUCTION DE CARTE NATIONALE D\'IDENTITE</span></p></body></html>"))
        self.labPhoto.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Photo</p></body></html>"))
        self.email.setPlaceholderText(_translate("MainWindow", "Entrez l\'email"))
        self.email_Label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Email</span></p><p><br/></p></body></html>"))
        self.listeEnregistrement.setTabText(self.listeEnregistrement.indexOf(self.tab), _translate("MainWindow", "enregistrement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
